export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const APPLY_NEW_SETTINGS = "APPLY_NEW_SETTINGS";
export const CARD_INFO = "CARD_INFO";
export const SET_INPUT_SEARCH_TEXT = "SET_INPUT_SEARCH_TEXT";
export const INCREASE_AMOUNT_OF_CARDS = "INCREASE_AMOUNT_OF_CARDS";
